// const expr=require('express')
// const app=expr()
// app.get('/:id',(req,res)=>{
//     res.set('Content-Type','text/plain')
//     res.write('Your user id is='+ req.params.id)
//     res.send()
// })
// app.get('/:userId/:uId/test/:test',(req,res)=>{
//     res.set('Content-Type','text/plain')
//     res.write('Your user id is='+ req.params.userId)
//     res.send()
// })
// app.get('/things/:item/:id',(req,res)=>{
//     res.set('Content-Type','text/plain')
//     res.write('Your user id is='+ req.params.item)
//     res.write('Your user id is='+ req.params.id)
//     res.send()
// })
// app.get('/flight/:from-:to',(req,res)=>{
//     res.set('Content-Type','text/plain')
//     res.write('Your user id is='+ req.params.from)
//     res.write('Your user id is='+ req.params.to)
//     res.send()
// })
// app.listen(3001)
